-- AlterTable
ALTER TABLE "Employee" ALTER COLUMN "nationalId" DROP NOT NULL,
ALTER COLUMN "phoneNo" DROP NOT NULL,
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "hireDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "currency" SET DEFAULT 'GBP';
